In [1]:
from sklearn import tree
import pandas as pd
import os

In [2]:
df = pd.read_csv(os.path.join("Resources", "testing.csv"))
df.head()

,Year,GCAG,GISTEMP,Average Land Temperature (Degrees Celcius),c-C4F8,C2F6,C3F8,C4F10,C5F12,C6F14,...,HFC245fa,HFC365mfc,HFC4310mee,CH4,CH3Br,CH3Cl,NF3,N20,SF6,SO2F2
0,1880,-0.1148,-0.20,8.118750,0.0,0.000349,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,868.696106,5.299998,457.0,0.0,277.265047,0.0,0.000028
1,1881,-0.0628,-0.12,8.270917,0.0,0.000363,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,870.984127,5.299998,457.0,0.0,277.374049,0.0,0.000029
2,1882,-0.0648,-0.10,8.128917,0.0,0.000377,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,873.250134,5.299998,457.0,0.0,277.486048,0.0,0.000029
3,1883,-0.1424,-0.21,7.976917,0.0,0.000392,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,875.603151,5.299998,457.0,0.0,277.591048,0.0,0.000029
4,1884,-0.2009,-0.28,7.773667,0.0,0.000407,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,878.148195,5.299998,457.0,0.0,277.695048,0.0,0.000029

In [3]:
target = df["Average Land Temperature (Degrees Celcius)"]

In [4]:
clean_data = df.drop(["Average Land Temperature (Degrees Celcius)", "GISTEMP", "GCAG", "Year"], axis=1)
feature_names = clean_data.columns
clean_data.head()

,c-C4F8,C2F6,C3F8,C4F10,C5F12,C6F14,C7F16,C8F18,CO2,CCl4,...,HFC245fa,HFC365mfc,HFC4310mee,CH4,CH3Br,CH3Cl,NF3,N20,SF6,SO2F2
0,0.0,0.000349,0.0,0.0,0.0,0.0,0.0,0.0,289.469999,0.025,...,0.0,0.0,0.0,868.696106,5.299998,457.0,0.0,277.265047,0.0,0.000028
1,0.0,0.000363,0.0,0.0,0.0,0.0,0.0,0.0,289.736999,0.025,...,0.0,0.0,0.0,870.984127,5.299998,457.0,0.0,277.374049,0.0,0.000029
2,0.0,0.000377,0.0,0.0,0.0,0.0,0.0,0.0,290.018999,0.025,...,0.0,0.0,0.0,873.250134,5.299998,457.0,0.0,277.486048,0.0,0.000029
3,0.0,0.000392,0.0,0.0,0.0,0.0,0.0,0.0,290.262999,0.025,...,0.0,0.0,0.0,875.603151,5.299998,457.0,0.0,277.591048,0.0,0.000029
4,0.0,0.000407,0.0,0.0,0.0,0.0,0.0,0.0,290.511999,0.025,...,0.0,0.0,0.0,878.148195,5.299998,457.0,0.0,277.695048,0.0,0.000029

In [5]:
# Convert to numpy arrays
import numpy as np

features = np.array(clean_data)
target_final = np.array(target)

# Training and Testing Sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target_final, random_state = 42)

In [6]:
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.605627833556759

In [7]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.8749939665460031

In [8]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.24601252303827978, 'HFC365mfc'),
 (0.06650704132140456, 'HFC227ea'),
 (0.05102121534732119, 'C2F6'),
 (0.04926551651762968, 'Halon1211'),
 (0.04602911190775468, 'C3F8'),
 (0.041965386732672104, 'CH4'),
 (0.0359517200633751, 'HFC32'),
 (0.035528736703301644, 'CH3Br'),
 (0.03454578625896374, 'SO2F2'),
 (0.029531091829883713, 'N20'),
 (0.02918908389672703, 'HFC152a'),
 (0.026387847288880373, 'CCl4'),
 (0.024673245687959578, 'CO2'),
 (0.0212788988225076, 'CHCl3'),
 (0.02074621784986354, 'CF4'),
 (0.019870942777450742, 'HFC23'),
 (0.019142906872392416, 'SF6'),
 (0.01727993806211338, 'CFC12'),
 (0.01563435685169345, 'NF3'),
 (0.01360265218092906, 'C5F12'),
 (0.01226863772378194, 'CFC115'),
 (0.012216317037013986, 'CH2Cl2'),
 (0.012162606025362675, 'Halon1301'),
 (0.011376275597378627, 'C7F16'),
 (0.010903634703724588, 'C6F14'),
 (0.010779150834717666, 'CFC114'),
 (0.009833469907676655, 'CFC113'),
 (0.008145846592350157, 'c-C4F8'),
 (0.007571327366093354, 'HCFC22'),
 (0.0069938028132939456, 'C8F18'),
 (0.006186904985829389, 'CH3CCl3'),
 (0.0055779159152789075, 'HFC236fa'),
 (0.0055690289221895575, 'HFC134a'),
 (0.004637760285079654, 'C4F10'),
 (0.00462774053260417, 'HFC143a'),
 (0.00457511123335154, 'HFC125'),
 (0.00448406604634034, 'HFC4310mee'),
 (0.004350904750202281, 'HCFC142b'),
 (0.004239025395113373, 'CFC11'),
 (0.004047019268746452, 'CH3Cl'),
 (0.003467344707839653, 'Halon2402'),
 (0.0009458729453480552, 'HFC245fa'),
 (0.0008760163995796013, 'HCFC141b')]